/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service.criteria;

/**
 * Criteria bean used for Danhmuc search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class DanhmucCriteria {

    private String tendanhmuc; 
	// Constructor
	public DanhmucCriteria() {
		// Needed empty constructor for serialization
	}

	public void setTendanhmuc(String tendanhmuc) {this.tendanhmuc = tendanhmuc;}
	public String getTendanhmuc() {return this.tendanhmuc;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(tendanhmuc); 
        return sb.toString();
	}
}
