/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service.criteria;

/**
 * Criteria bean used for Dinhky search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class DinhkyCriteria {

    private String chieucao; 
    private String cannang; 
    private String huyetap; 
    private String loaisuckhoe; 
    private String ketluan; 
    private String chuandoan; 
	// Constructor
	public DinhkyCriteria() {
		// Needed empty constructor for serialization
	}

	public void setChieucao(String chieucao) {this.chieucao = chieucao;}
	public String getChieucao() {return this.chieucao;}
	public void setCannang(String cannang) {this.cannang = cannang;}
	public String getCannang() {return this.cannang;}
	public void setHuyetap(String huyetap) {this.huyetap = huyetap;}
	public String getHuyetap() {return this.huyetap;}
	public void setLoaisuckhoe(String loaisuckhoe) {this.loaisuckhoe = loaisuckhoe;}
	public String getLoaisuckhoe() {return this.loaisuckhoe;}
	public void setKetluan(String ketluan) {this.ketluan = ketluan;}
	public String getKetluan() {return this.ketluan;}
	public void setChuandoan(String chuandoan) {this.chuandoan = chuandoan;}
	public String getChuandoan() {return this.chuandoan;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(chieucao); 
		sb.append("|"); 
		sb.append(cannang); 
		sb.append("|"); 
		sb.append(huyetap); 
		sb.append("|"); 
		sb.append(loaisuckhoe); 
		sb.append("|"); 
		sb.append(ketluan); 
		sb.append("|"); 
		sb.append(chuandoan); 
        return sb.toString();
	}
}
