/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service.criteria;

/**
 * Criteria bean used for Hocki search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class HockiCriteria {

    private String tenhocki; 
	// Constructor
	public HockiCriteria() {
		// Needed empty constructor for serialization
	}

	public void setTenhocki(String tenhocki) {this.tenhocki = tenhocki;}
	public String getTenhocki() {return this.tenhocki;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(tenhocki); 
        return sb.toString();
	}
}
