/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service.criteria;

/**
 * Criteria bean used for Nhasanxuat search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class NhasanxuatCriteria {

    private String tennhasanxuat; 
	// Constructor
	public NhasanxuatCriteria() {
		// Needed empty constructor for serialization
	}

	public void setTennhasanxuat(String tennhasanxuat) {this.tennhasanxuat = tennhasanxuat;}
	public String getTennhasanxuat() {return this.tennhasanxuat;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(tennhasanxuat); 
        return sb.toString();
	}
}
