/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service.criteria;

/**
 * Criteria bean used for Role search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class RoleCriteria {

    private String name; 
	// Constructor
	public RoleCriteria() {
		// Needed empty constructor for serialization
	}

	public void setName(String name) {this.name = name;}
	public String getName() {return this.name;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(name); 
        return sb.toString();
	}
}
