/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service.criteria;

/**
 * Criteria bean used for Sucosuckhoe search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class SucosuckhoeCriteria {

    private String ngay; 
    private String loaisuco; 
    private String bienphap; 
    private String mucdo; 
    private String nguoixuly; 
	// Constructor
	public SucosuckhoeCriteria() {
		// Needed empty constructor for serialization
	}

	public void setNgay(String ngay) {this.ngay = ngay;}
	public String getNgay() {return this.ngay;}
	public void setLoaisuco(String loaisuco) {this.loaisuco = loaisuco;}
	public String getLoaisuco() {return this.loaisuco;}
	public void setBienphap(String bienphap) {this.bienphap = bienphap;}
	public String getBienphap() {return this.bienphap;}
	public void setMucdo(String mucdo) {this.mucdo = mucdo;}
	public String getMucdo() {return this.mucdo;}
	public void setNguoixuly(String nguoixuly) {this.nguoixuly = nguoixuly;}
	public String getNguoixuly() {return this.nguoixuly;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(ngay); 
		sb.append("|"); 
		sb.append(loaisuco); 
		sb.append("|"); 
		sb.append(bienphap); 
		sb.append("|"); 
		sb.append(mucdo); 
		sb.append("|"); 
		sb.append(nguoixuly); 
        return sb.toString();
	}
}
