/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service.criteria;

/**
 * Criteria bean used for Thuoc search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class ThuocCriteria {

    private String tenthuoc; 
    private String tacdung; 
    private String cachdung; 
    private String ngaynhap; 
	// Constructor
	public ThuocCriteria() {
		// Needed empty constructor for serialization
	}

	public void setTenthuoc(String tenthuoc) {this.tenthuoc = tenthuoc;}
	public String getTenthuoc() {return this.tenthuoc;}
	public void setTacdung(String tacdung) {this.tacdung = tacdung;}
	public String getTacdung() {return this.tacdung;}
	public void setCachdung(String cachdung) {this.cachdung = cachdung;}
	public String getCachdung() {return this.cachdung;}
	public void setNgaynhap(String ngaynhap) {this.ngaynhap = ngaynhap;}
	public String getNgaynhap() {return this.ngaynhap;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(tenthuoc); 
		sb.append("|"); 
		sb.append(tacdung); 
		sb.append("|"); 
		sb.append(cachdung); 
		sb.append("|"); 
		sb.append(ngaynhap); 
        return sb.toString();
	}
}
