/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service.criteria;

/**
 * Criteria bean used for Yte search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class YteCriteria {

    private String hoten; 
    private String gioitinh; 
    private String namsinh; 
    private String diachi; 
    private String socmt; 
    private String sodt; 
    private String chucvu; 
    private String tendangnhap; 
    private String matkhau; 
    private String ytecol; 
	// Constructor
	public YteCriteria() {
		// Needed empty constructor for serialization
	}

	public void setHoten(String hoten) {this.hoten = hoten;}
	public String getHoten() {return this.hoten;}
	public void setGioitinh(String gioitinh) {this.gioitinh = gioitinh;}
	public String getGioitinh() {return this.gioitinh;}
	public void setNamsinh(String namsinh) {this.namsinh = namsinh;}
	public String getNamsinh() {return this.namsinh;}
	public void setDiachi(String diachi) {this.diachi = diachi;}
	public String getDiachi() {return this.diachi;}
	public void setSocmt(String socmt) {this.socmt = socmt;}
	public String getSocmt() {return this.socmt;}
	public void setSodt(String sodt) {this.sodt = sodt;}
	public String getSodt() {return this.sodt;}
	public void setChucvu(String chucvu) {this.chucvu = chucvu;}
	public String getChucvu() {return this.chucvu;}
	public void setTendangnhap(String tendangnhap) {this.tendangnhap = tendangnhap;}
	public String getTendangnhap() {return this.tendangnhap;}
	public void setMatkhau(String matkhau) {this.matkhau = matkhau;}
	public String getMatkhau() {return this.matkhau;}
	public void setYtecol(String ytecol) {this.ytecol = ytecol;}
	public String getYtecol() {return this.ytecol;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(hoten); 
		sb.append("|"); 
		sb.append(gioitinh); 
		sb.append("|"); 
		sb.append(namsinh); 
		sb.append("|"); 
		sb.append(diachi); 
		sb.append("|"); 
		sb.append(socmt); 
		sb.append("|"); 
		sb.append(sodt); 
		sb.append("|"); 
		sb.append(chucvu); 
		sb.append("|"); 
		sb.append(tendangnhap); 
		sb.append("|"); 
		sb.append(matkhau); 
		sb.append("|"); 
		sb.append(ytecol); 
        return sb.toString();
	}
}
