/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 22:38:43 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.controller;

import com.tlu.qlsuckhoe.entity.Yte;
import com.tlu.qlsuckhoe.service.YteServiceImpl;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@CrossOrigin(origins = "*")
@RequestMapping(value = "/yte", produces = "application/hal+json")
public class YteController {

	private static final Logger LOGGER = LoggerFactory.getLogger(YteController.class);

	private static final String NOT_FOUND ="Yte not found";

	@Autowired
	private YteServiceImpl yteService;

	@RequestMapping(value = "/",
			produces = {MediaType.APPLICATION_JSON_VALUE})
	public List<Yte> findAll() {
		List<Yte> list = yteService.findAll();
		return list;
	}


	@GetMapping("{idyte}")
	public Yte get(@PathVariable("idyte") Integer idyte) {
		final Yte yte = yteService.getOne(idyte);
		LOGGER.info("Yte found : {}", yte);
		return yte;
	}

	@PostMapping(consumes = "application/json")
	public Yte create(@RequestBody Yte yte) {
		LOGGER.info("Yte creation request : {}", yte);
		if (yteService.exist(yte)) {
			LOGGER.info("Yte already exist ! : {}", yte);
			return null;
		} else {
			final Yte created = yteService.create(yte);
			LOGGER.info("Created yte {}", created);
			return created;
		}
	}

	@PutMapping(value = "{idyte}", consumes = "application/json")
	public Yte update(@PathVariable("idyte") Integer idyte, @RequestBody Yte yte) {
		return yteService.update(yte);
	}

	@DeleteMapping("{idyte}")
	public void delete(@PathVariable("idyte") Integer idyte) {
		LOGGER.info("Yte deletion request : {}", resolveIdForLogger(idyte));
		if (yteService.delete(idyte)) {
			LOGGER.info("Yte succesfully deleted");
		} else {
			LOGGER.info(NOT_FOUND);
		}
	}

	private String resolveIdForLogger(Integer idyte) {
		final StringBuilder ids = new StringBuilder();
		ids.append(String.valueOf(idyte));
		return ids.toString();
	}

}

