/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:53 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;

import com.tlu.qlsuckhoe.entity.Admin;
import java.util.List;

public interface AdminService {

	public Admin getOne(Integer idadmin);

	public List<Admin> findAll();

	public Boolean delete(Integer idadmin);

	public Admin create(Admin admin);

	public Admin update(Admin admin);

	public Boolean exist(Admin admin);
}
