/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 22:38:41 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;

import com.tlu.qlsuckhoe.entity.Benh;

import java.util.List;

public interface BenhService {

	public Benh getOne(Integer idbenh);

	public List<Benh> findAll();

	public Boolean delete(Integer idbenh);

	public Benh create(Benh benh);

	public Benh update(Benh benh);

	public Boolean exist(Benh benh);
}
