/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;



import java.util.List;

import javax.transaction.Transactional;

import com.tlu.qlsuckhoe.repository.BenhRepository;
import com.tlu.qlsuckhoe.entity.Benh;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class BenhServiceImpl implements BenhService {

	@Autowired
	private BenhRepository benhRepository;

	@Override
	public Benh getOne(Integer idbenh) {
		return benhRepository.getOne(idbenh);
	}

	@Override
	public Boolean delete(Integer idbenh) {
		if (benhRepository.getOne(idbenh) != null) {
			benhRepository.deleteById(idbenh);
			return true;
		}
		return false;
	}

	@Override
	public Benh create(Benh benh) {
		return benhRepository.save(benh);
	}

	@Override
	public Benh update(Benh benhToUpdate) {
						Benh benh = benhRepository.getOne(benhToUpdate.getIdbenh());
																						
				if(benhToUpdate.getIddanhmuc() !=null) {
			
		}
				if(benhToUpdate.getTenbenh() !=null) {
			
		}
				if(benhToUpdate.getTrieuchung() !=null) {
			
		}
				if(benhToUpdate.getCachchua() !=null) {
			
		}
				return benhRepository.save(benh);
	}

	@Override
	public Boolean exist(Benh benh) {
						return benhRepository.existsById(benh.getIdbenh());
																					}

	@Override
	public List<Benh> findAll() {
		return benhRepository.findAll();
	}

}

