/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;



import java.util.List;

import javax.transaction.Transactional;

import com.tlu.qlsuckhoe.repository.DanhmucRepository;
import com.tlu.qlsuckhoe.entity.Danhmuc;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class DanhmucServiceImpl implements DanhmucService {

	@Autowired
	private DanhmucRepository danhmucRepository;

	@Override
	public Danhmuc getOne(Integer iddanhmuc) {
		return danhmucRepository.getOne(iddanhmuc);
	}

	@Override
	public Boolean delete(Integer iddanhmuc) {
		if (danhmucRepository.getOne(iddanhmuc) != null) {
			danhmucRepository.deleteById(iddanhmuc);
			return true;
		}
		return false;
	}

	@Override
	public Danhmuc create(Danhmuc danhmuc) {
		return danhmucRepository.save(danhmuc);
	}

	@Override
	public Danhmuc update(Danhmuc danhmucToUpdate) {
						Danhmuc danhmuc = danhmucRepository.getOne(danhmucToUpdate.getIddanhmuc());
										
				if(danhmucToUpdate.getTendanhmuc() !=null) {
			
		}
				return danhmucRepository.save(danhmuc);
	}

	@Override
	public Boolean exist(Danhmuc danhmuc) {
						return danhmucRepository.existsById(danhmuc.getIddanhmuc());
									}

	@Override
	public List<Danhmuc> findAll() {
		return danhmucRepository.findAll();
	}

}

