/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;

import com.tlu.qlsuckhoe.entity.Danhmuc;
import java.util.List;

public interface DanhmucService {

	public Danhmuc getOne(Integer iddanhmuc);

	public List<Danhmuc> findAll();

	public Boolean delete(Integer iddanhmuc);

	public Danhmuc create(Danhmuc danhmuc);

	public Danhmuc update(Danhmuc danhmuc);

	public Boolean exist(Danhmuc danhmuc);
}
