/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;



import java.util.List;

import javax.transaction.Transactional;

import com.tlu.qlsuckhoe.repository.DinhkyRepository;
import com.tlu.qlsuckhoe.entity.Dinhky;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class DinhkyServiceImpl implements DinhkyService {

	@Autowired
	private DinhkyRepository dinhkyRepository;

	@Override
	public Dinhky getOne(Integer idkhamdinhky) {
		return dinhkyRepository.getOne(idkhamdinhky);
	}

	@Override
	public Boolean delete(Integer idkhamdinhky) {
		if (dinhkyRepository.getOne(idkhamdinhky) != null) {
			dinhkyRepository.deleteById(idkhamdinhky);
			return true;
		}
		return false;
	}

	@Override
	public Dinhky create(Dinhky dinhky) {
		return dinhkyRepository.save(dinhky);
	}

	@Override
	public Dinhky update(Dinhky dinhkyToUpdate) {
						Dinhky dinhky = dinhkyRepository.getOne(dinhkyToUpdate.getIdkhamdinhky());
																																										
				if(dinhkyToUpdate.getIdsinhvien() !=null) {
			
		}
				if(dinhkyToUpdate.getIdhocki() !=null) {
			
		}
				if(dinhkyToUpdate.getIdbenh() !=null) {
			
		}
				if(dinhkyToUpdate.getChieucao() !=null) {
			
		}
				if(dinhkyToUpdate.getCannang() !=null) {
			
		}
				if(dinhkyToUpdate.getHuyetap() !=null) {
			
		}
				if(dinhkyToUpdate.getLoaisuckhoe() !=null) {
			
		}
				if(dinhkyToUpdate.getKetluan() !=null) {
			
		}
				if(dinhkyToUpdate.getChuandoan() !=null) {
			
		}
				return dinhkyRepository.save(dinhky);
	}

	@Override
	public Boolean exist(Dinhky dinhky) {
						return dinhkyRepository.existsById(dinhky.getIdkhamdinhky());
																																									}

	@Override
	public List<Dinhky> findAll() {
		return dinhkyRepository.findAll();
	}

}

