/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 22:38:41 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;

import com.tlu.qlsuckhoe.entity.Dinhky;

import java.util.List;

public interface DinhkyService {

	public Dinhky getOne(Integer idkhamdinhky);

	public List<Dinhky> findAll();

	public Boolean delete(Integer idkhamdinhky);

	public Dinhky create(Dinhky dinhky);

	public Dinhky update(Dinhky dinhky);

	public Boolean exist(Dinhky dinhky);
}
