/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 22:38:41 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;


import com.tlu.qlsuckhoe.entity.Dinhky;
import com.tlu.qlsuckhoe.repository.DinhkyRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import javax.transaction.Transactional;
import java.util.List;

@Service
@Transactional
public class DinhkyServiceImpl implements DinhkyService {

	@Autowired
	private DinhkyRepository dinhkyRepository;

	@Override
	public Dinhky getOne(Integer idkhamdinhky) {
		return dinhkyRepository.findById(idkhamdinhky).get();
	}

	@Override
	public Boolean delete(Integer idkhamdinhky) {
		if (dinhkyRepository.getOne(idkhamdinhky) != null) {
			dinhkyRepository.deleteById(idkhamdinhky);
			return true;
		}
		return false;
	}

	@Override
	public Dinhky create(Dinhky dinhky) {
		return dinhkyRepository.save(dinhky);
	}

	@Override
	public Dinhky update(Dinhky dinhkyToUpdate) {
						Dinhky dinhky = dinhkyRepository.getOne(dinhkyToUpdate.getIdkhamdinhky());

		if (dinhkyToUpdate.getBenh() != null) {
			
		}
		if (dinhkyToUpdate.getHocki() != null) {
			
		}
		if (dinhkyToUpdate.getSinhvien() != null) {
			
		}
				if(dinhkyToUpdate.getChieucao() !=null) {
			
		}
				if(dinhkyToUpdate.getCannang() !=null) {
			
		}
				if(dinhkyToUpdate.getHuyetap() !=null) {
			
		}
				if(dinhkyToUpdate.getLoaisuckhoe() !=null) {
			
		}
				if(dinhkyToUpdate.getKetluan() !=null) {
			
		}
				if(dinhkyToUpdate.getChuandoan() !=null) {
			
		}
				return dinhkyRepository.save(dinhky);
	}

	@Override
	public Boolean exist(Dinhky dinhky) {
						return dinhkyRepository.existsById(dinhky.getIdkhamdinhky());
																																									}

	@Override
	public List<Dinhky> findAll() {
		return dinhkyRepository.findAll();
	}

}


