/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;

import com.tlu.qlsuckhoe.entity.Hocki;

import java.util.List;

public interface HockiService {

	public Hocki getOne(Integer idhocki);

	public List<Hocki> findAll();

	public Boolean delete(Integer idhocki);

	public Hocki create(Hocki hocki);

	public Hocki update(Hocki hocki);

	public Boolean exist(Hocki hocki);
}
