/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;



import java.util.List;

import javax.transaction.Transactional;

import com.tlu.qlsuckhoe.repository.HockiRepository;
import com.tlu.qlsuckhoe.entity.Hocki;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class HockiServiceImpl implements HockiService {

	@Autowired
	private HockiRepository hockiRepository;

	@Override
	public Hocki getOne(Integer idhocki) {
		return hockiRepository.getOne(idhocki);
	}

	@Override
	public Boolean delete(Integer idhocki) {
		if (hockiRepository.getOne(idhocki) != null) {
			hockiRepository.deleteById(idhocki);
			return true;
		}
		return false;
	}

	@Override
	public Hocki create(Hocki hocki) {
		return hockiRepository.save(hocki);
	}

	@Override
	public Hocki update(Hocki hockiToUpdate) {
						Hocki hocki = hockiRepository.getOne(hockiToUpdate.getIdhocki());
										
				if(hockiToUpdate.getTenhocki() !=null) {
			
		}
				return hockiRepository.save(hocki);
	}

	@Override
	public Boolean exist(Hocki hocki) {
						return hockiRepository.existsById(hocki.getIdhocki());
									}

	@Override
	public List<Hocki> findAll() {
		return hockiRepository.findAll();
	}

}

