/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 22:38:42 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;


import com.tlu.qlsuckhoe.entity.Loaithuoc;
import com.tlu.qlsuckhoe.repository.LoaithuocRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import javax.transaction.Transactional;
import java.util.List;

@Service
@Transactional
public class LoaithuocServiceImpl implements LoaithuocService {

	@Autowired
	private LoaithuocRepository loaithuocRepository;

	@Override
	public Loaithuoc getOne(Integer idloaithuoc) {
		return loaithuocRepository.findById(idloaithuoc).get();
	}

	@Override
	public Boolean delete(Integer idloaithuoc) {
		if (loaithuocRepository.getOne(idloaithuoc) != null) {
			loaithuocRepository.deleteById(idloaithuoc);
			return true;
		}
		return false;
	}

	@Override
	public Loaithuoc create(Loaithuoc loaithuoc) {
		return loaithuocRepository.save(loaithuoc);
	}

	@Override
	public Loaithuoc update(Loaithuoc loaithuocToUpdate) {
						Loaithuoc loaithuoc = loaithuocRepository.getOne(loaithuocToUpdate.getIdloaithuoc());
										
				if(loaithuocToUpdate.getTenloai() !=null) {
			
		}
				return loaithuocRepository.save(loaithuoc);
	}

	@Override
	public Boolean exist(Loaithuoc loaithuoc) {
						return loaithuocRepository.existsById(loaithuoc.getIdloaithuoc());
									}

	@Override
	public List<Loaithuoc> findAll() {
		return loaithuocRepository.findAll();
	}

}


