/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;

import com.tlu.qlsuckhoe.entity.Nhasanxuat;
import java.util.List;

public interface NhasanxuatService {

	public Nhasanxuat getOne(Integer idnhasanxuat);

	public List<Nhasanxuat> findAll();

	public Boolean delete(Integer idnhasanxuat);

	public Nhasanxuat create(Nhasanxuat nhasanxuat);

	public Nhasanxuat update(Nhasanxuat nhasanxuat);

	public Boolean exist(Nhasanxuat nhasanxuat);
}
