/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 22:38:42 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;


import com.tlu.qlsuckhoe.entity.Nhasanxuat;
import com.tlu.qlsuckhoe.repository.NhasanxuatRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import javax.transaction.Transactional;
import java.util.List;

@Service
@Transactional
public class NhasanxuatServiceImpl implements NhasanxuatService {

	@Autowired
	private NhasanxuatRepository nhasanxuatRepository;

	@Override
	public Nhasanxuat getOne(Integer idnhasanxuat) {
		return nhasanxuatRepository.findById(idnhasanxuat).get();
	}

	@Override
	public Boolean delete(Integer idnhasanxuat) {
		if (nhasanxuatRepository.getOne(idnhasanxuat) != null) {
			nhasanxuatRepository.deleteById(idnhasanxuat);
			return true;
		}
		return false;
	}

	@Override
	public Nhasanxuat create(Nhasanxuat nhasanxuat) {
		return nhasanxuatRepository.save(nhasanxuat);
	}

	@Override
	public Nhasanxuat update(Nhasanxuat nhasanxuatToUpdate) {
						Nhasanxuat nhasanxuat = nhasanxuatRepository.getOne(nhasanxuatToUpdate.getIdnhasanxuat());
										
				if(nhasanxuatToUpdate.getTennhasanxuat() !=null) {
			
		}
				return nhasanxuatRepository.save(nhasanxuat);
	}

	@Override
	public Boolean exist(Nhasanxuat nhasanxuat) {
						return nhasanxuatRepository.existsById(nhasanxuat.getIdnhasanxuat());
									}

	@Override
	public List<Nhasanxuat> findAll() {
		return nhasanxuatRepository.findAll();
	}

}


