/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;



import java.util.List;

import javax.transaction.Transactional;

import com.tlu.qlsuckhoe.entity.Role;
import com.tlu.qlsuckhoe.repository.RoleRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class RoleServiceImpl implements RoleService {

	@Autowired
	private RoleRepository roleRepository;

	@Override
	public Role getOne(Integer idrole) {
		return roleRepository.getOne(idrole);
	}

	@Override
	public Boolean delete(Integer idrole) {
		if (roleRepository.getOne(idrole) != null) {
			roleRepository.deleteById(idrole);
			return true;
		}
		return false;
	}

	@Override
	public Role create(Role role) {
		return roleRepository.save(role);
	}

	@Override
	public Role update(Role roleToUpdate) {
						Role role = roleRepository.getOne(roleToUpdate.getIdrole());
										
				if(roleToUpdate.getName() !=null) {
			
		}
				return roleRepository.save(role);
	}

	@Override
	public Boolean exist(Role role) {
						return roleRepository.existsById(role.getIdrole());
									}

	@Override
	public List<Role> findAll() {
		return roleRepository.findAll();
	}

}

