/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 22:38:42 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;


import com.tlu.qlsuckhoe.entity.Sinhvien;
import com.tlu.qlsuckhoe.repository.SinhvienRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import javax.transaction.Transactional;
import java.util.List;

@Service
@Transactional
public class SinhvienServiceImpl implements SinhvienService {

	@Autowired
	private SinhvienRepository sinhvienRepository;

	@Override
	public Sinhvien getOne(Integer idsinhvien) {
		return sinhvienRepository.findById(idsinhvien).get();
	}

	@Override
	public Boolean delete(Integer idsinhvien) {
		if (sinhvienRepository.getOne(idsinhvien) != null) {
			sinhvienRepository.deleteById(idsinhvien);
			return true;
		}
		return false;
	}

	@Override
	public Sinhvien create(Sinhvien sinhvien) {
		return sinhvienRepository.save(sinhvien);
	}

	@Override
	public Sinhvien update(Sinhvien sinhvienToUpdate) {
						Sinhvien sinhvien = sinhvienRepository.getOne(sinhvienToUpdate.getIdsinhvien());
																																														
				if(sinhvienToUpdate.getHoten() !=null) {
			
		}
				if(sinhvienToUpdate.getGioitinh() !=null) {
			
		}
				if(sinhvienToUpdate.getNamsinh() !=null) {
			
		}
				if(sinhvienToUpdate.getSocmt() !=null) {
			
		}
				if(sinhvienToUpdate.getDiachi() !=null) {
			
		}
				if(sinhvienToUpdate.getChuyennganh() !=null) {
			
		}
				if(sinhvienToUpdate.getKhoa() !=null) {
			
		}
				if(sinhvienToUpdate.getMasv() !=null) {
			
		}
				if(sinhvienToUpdate.getMatkhau() !=null) {
			
		}
		if (sinhvienToUpdate.getRole() != null) {
			
		}
				return sinhvienRepository.save(sinhvien);
	}

	@Override
	public Boolean exist(Sinhvien sinhvien) {
						return sinhvienRepository.existsById(sinhvien.getIdsinhvien());
																																													}

	@Override
	public List<Sinhvien> findAll() {
		return sinhvienRepository.findAll();
	}

}


