/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 22:38:42 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;


import com.tlu.qlsuckhoe.entity.Sucosuckhoe;
import com.tlu.qlsuckhoe.repository.SucosuckhoeRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import javax.transaction.Transactional;
import java.util.List;

@Service
@Transactional
public class SucosuckhoeServiceImpl implements SucosuckhoeService {

	@Autowired
	private SucosuckhoeRepository sucosuckhoeRepository;

	@Override
	public Sucosuckhoe getOne(Integer idsucosuckhoe) {
		return sucosuckhoeRepository.findById(idsucosuckhoe).get();
	}

	@Override
	public Boolean delete(Integer idsucosuckhoe) {
		if (sucosuckhoeRepository.getOne(idsucosuckhoe) != null) {
			sucosuckhoeRepository.deleteById(idsucosuckhoe);
			return true;
		}
		return false;
	}

	@Override
	public Sucosuckhoe create(Sucosuckhoe sucosuckhoe) {
		return sucosuckhoeRepository.save(sucosuckhoe);
	}

	@Override
	public Sucosuckhoe update(Sucosuckhoe sucosuckhoeToUpdate) {
						Sucosuckhoe sucosuckhoe = sucosuckhoeRepository.getOne(sucosuckhoeToUpdate.getIdsucosuckhoe());

		if (sucosuckhoeToUpdate.getSinhvien() != null) {
			
		}
				if(sucosuckhoeToUpdate.getNgay() !=null) {
			
		}
				if(sucosuckhoeToUpdate.getLoaisuco() !=null) {
			
		}
				if(sucosuckhoeToUpdate.getBienphap() !=null) {
			
		}
				if(sucosuckhoeToUpdate.getMucdo() !=null) {
			
		}
				if(sucosuckhoeToUpdate.getNguoixuly() !=null) {
			
		}
		if (sucosuckhoeToUpdate.getThuoc() != null) {
			
		}
				if(sucosuckhoeToUpdate.getIdthietbiyte() !=null) {
			
		}
				return sucosuckhoeRepository.save(sucosuckhoe);
	}

	@Override
	public Boolean exist(Sucosuckhoe sucosuckhoe) {
						return sucosuckhoeRepository.existsById(sucosuckhoe.getIdsucosuckhoe());
																																					}

	@Override
	public List<Sucosuckhoe> findAll() {
		return sucosuckhoeRepository.findAll();
	}

}


