/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;



import java.util.List;

import javax.transaction.Transactional;

import com.tlu.qlsuckhoe.repository.SucosuckhoeRepository;
import com.tlu.qlsuckhoe.entity.Sucosuckhoe;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class SucosuckhoeServiceImpl implements SucosuckhoeService {

	@Autowired
	private SucosuckhoeRepository sucosuckhoeRepository;

	@Override
	public Sucosuckhoe getOne(Integer idsucosuckhoe) {
		return sucosuckhoeRepository.getOne(idsucosuckhoe);
	}

	@Override
	public Boolean delete(Integer idsucosuckhoe) {
		if (sucosuckhoeRepository.getOne(idsucosuckhoe) != null) {
			sucosuckhoeRepository.deleteById(idsucosuckhoe);
			return true;
		}
		return false;
	}

	@Override
	public Sucosuckhoe create(Sucosuckhoe sucosuckhoe) {
		return sucosuckhoeRepository.save(sucosuckhoe);
	}

	@Override
	public Sucosuckhoe update(Sucosuckhoe sucosuckhoeToUpdate) {
						Sucosuckhoe sucosuckhoe = sucosuckhoeRepository.getOne(sucosuckhoeToUpdate.getIdsucosuckhoe());
																																						
				if(sucosuckhoeToUpdate.getIdsinhvien() !=null) {
			
		}
				if(sucosuckhoeToUpdate.getNgay() !=null) {
			
		}
				if(sucosuckhoeToUpdate.getLoaisuco() !=null) {
			
		}
				if(sucosuckhoeToUpdate.getBienphap() !=null) {
			
		}
				if(sucosuckhoeToUpdate.getMucdo() !=null) {
			
		}
				if(sucosuckhoeToUpdate.getNguoixuly() !=null) {
			
		}
				if(sucosuckhoeToUpdate.getIdthuoc() !=null) {
			
		}
				if(sucosuckhoeToUpdate.getIdthietbiyte() !=null) {
			
		}
				return sucosuckhoeRepository.save(sucosuckhoe);
	}

	@Override
	public Boolean exist(Sucosuckhoe sucosuckhoe) {
						return sucosuckhoeRepository.existsById(sucosuckhoe.getIdsucosuckhoe());
																																					}

	@Override
	public List<Sucosuckhoe> findAll() {
		return sucosuckhoeRepository.findAll();
	}

}

