/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 22:38:43 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;


import com.tlu.qlsuckhoe.entity.Thietbiyte;
import com.tlu.qlsuckhoe.repository.ThietbiyteRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import javax.transaction.Transactional;
import java.util.List;

@Service
@Transactional
public class ThietbiyteServiceImpl implements ThietbiyteService {

	@Autowired
	private ThietbiyteRepository thietbiyteRepository;

	@Override
	public Thietbiyte getOne(Integer idthietbiyte) {
		return thietbiyteRepository.findById(idthietbiyte).get();
	}

	@Override
	public Boolean delete(Integer idthietbiyte) {
		if (thietbiyteRepository.getOne(idthietbiyte) != null) {
			thietbiyteRepository.deleteById(idthietbiyte);
			return true;
		}
		return false;
	}

	@Override
	public Thietbiyte create(Thietbiyte thietbiyte) {
		return thietbiyteRepository.save(thietbiyte);
	}

	@Override
	public Thietbiyte update(Thietbiyte thietbiyteToUpdate) {
						Thietbiyte thietbiyte = thietbiyteRepository.getOne(thietbiyteToUpdate.getIdthietbiyte());

		if (thietbiyteToUpdate.getNhasanxuat() != null) {
			
		}
				if(thietbiyteToUpdate.getTenthietbi() !=null) {
			
		}
				if(thietbiyteToUpdate.getSoluong() !=null) {
			
		}
				if(thietbiyteToUpdate.getCachdung() !=null) {
			
		}
				return thietbiyteRepository.save(thietbiyte);
	}

	@Override
	public Boolean exist(Thietbiyte thietbiyte) {
						return thietbiyteRepository.existsById(thietbiyte.getIdthietbiyte());
																					}

	@Override
	public List<Thietbiyte> findAll() {
		return thietbiyteRepository.findAll();
	}

}


