/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 22:38:43 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;

import com.tlu.qlsuckhoe.entity.Thietbiyte;

import java.util.List;

public interface ThietbiyteService {

	public Thietbiyte getOne(Integer idthietbiyte);

	public List<Thietbiyte> findAll();

	public Boolean delete(Integer idthietbiyte);

	public Thietbiyte create(Thietbiyte thietbiyte);

	public Thietbiyte update(Thietbiyte thietbiyte);

	public Boolean exist(Thietbiyte thietbiyte);
}
