/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;



import java.util.List;

import javax.transaction.Transactional;

import com.tlu.qlsuckhoe.repository.ThuocRepository;
import com.tlu.qlsuckhoe.entity.Thuoc;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class ThuocServiceImpl implements ThuocService {

	@Autowired
	private ThuocRepository thuocRepository;

	@Override
	public Thuoc getOne(Integer idthuoc) {
		return thuocRepository.getOne(idthuoc);
	}

	@Override
	public Boolean delete(Integer idthuoc) {
		if (thuocRepository.getOne(idthuoc) != null) {
			thuocRepository.deleteById(idthuoc);
			return true;
		}
		return false;
	}

	@Override
	public Thuoc create(Thuoc thuoc) {
		return thuocRepository.save(thuoc);
	}

	@Override
	public Thuoc update(Thuoc thuocToUpdate) {
						Thuoc thuoc = thuocRepository.getOne(thuocToUpdate.getIdthuoc());
																																		
				if(thuocToUpdate.getIdloaithuoc() !=null) {
			
		}
				if(thuocToUpdate.getIdnhasanxuat() !=null) {
			
		}
				if(thuocToUpdate.getTenthuoc() !=null) {
			
		}
				if(thuocToUpdate.getTacdung() !=null) {
			
		}
				if(thuocToUpdate.getCachdung() !=null) {
			
		}
				if(thuocToUpdate.getNgaynhap() !=null) {
			
		}
				if(thuocToUpdate.getSoluong() !=null) {
			
		}
				return thuocRepository.save(thuoc);
	}

	@Override
	public Boolean exist(Thuoc thuoc) {
						return thuocRepository.existsById(thuoc.getIdthuoc());
																																	}

	@Override
	public List<Thuoc> findAll() {
		return thuocRepository.findAll();
	}

}

