/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 22:38:43 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;

import com.tlu.qlsuckhoe.entity.Tintuc;

import java.util.List;

public interface TintucService {

	public Tintuc getOne(Integer idtintuc);

	public List<Tintuc> findAll();

	public Boolean delete(Integer idtintuc);

	public Tintuc create(Tintuc tintuc);

	public Tintuc update(Tintuc tintuc);

	public Boolean exist(Tintuc tintuc);
}
