/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;



import java.util.List;

import javax.transaction.Transactional;

import com.tlu.qlsuckhoe.repository.TintucRepository;
import com.tlu.qlsuckhoe.entity.Tintuc;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class TintucServiceImpl implements TintucService {

	@Autowired
	private TintucRepository tintucRepository;

	@Override
	public Tintuc getOne(Integer idtintuc) {
		return tintucRepository.getOne(idtintuc);
	}

	@Override
	public Boolean delete(Integer idtintuc) {
		if (tintucRepository.getOne(idtintuc) != null) {
			tintucRepository.deleteById(idtintuc);
			return true;
		}
		return false;
	}

	@Override
	public Tintuc create(Tintuc tintuc) {
		return tintucRepository.save(tintuc);
	}

	@Override
	public Tintuc update(Tintuc tintucToUpdate) {
						Tintuc tintuc = tintucRepository.getOne(tintucToUpdate.getIdtintuc());
																		
				if(tintucToUpdate.getTieude() !=null) {
			
		}
				if(tintucToUpdate.getNgaydang() !=null) {
			
		}
				if(tintucToUpdate.getNoidung() !=null) {
			
		}
				return tintucRepository.save(tintuc);
	}

	@Override
	public Boolean exist(Tintuc tintuc) {
						return tintucRepository.existsById(tintuc.getIdtintuc());
																	}

	@Override
	public List<Tintuc> findAll() {
		return tintucRepository.findAll();
	}

}

