/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 22:38:43 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;


import com.tlu.qlsuckhoe.entity.Yte;
import com.tlu.qlsuckhoe.repository.YteRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import javax.transaction.Transactional;
import java.util.List;

@Service
@Transactional
public class YteServiceImpl implements YteService {

	@Autowired
	private YteRepository yteRepository;

	@Override
	public Yte getOne(Integer idyte) {
		return yteRepository.findById(idyte).get();
	}

	@Override
	public Boolean delete(Integer idyte) {
		if (yteRepository.getOne(idyte) != null) {
			yteRepository.deleteById(idyte);
			return true;
		}
		return false;
	}

	@Override
	public Yte create(Yte yte) {
		return yteRepository.save(yte);
	}

	@Override
	public Yte update(Yte yteToUpdate) {
						Yte yte = yteRepository.getOne(yteToUpdate.getIdyte());
																																																		
				if(yteToUpdate.getHoten() !=null) {
			
		}
				if(yteToUpdate.getGioitinh() !=null) {
			
		}
				if(yteToUpdate.getNamsinh() !=null) {
			
		}
				if(yteToUpdate.getDiachi() !=null) {
			
		}
				if(yteToUpdate.getSocmt() !=null) {
			
		}
				if(yteToUpdate.getSodt() !=null) {
			
		}
				if(yteToUpdate.getChucvu() !=null) {
			
		}
				if(yteToUpdate.getTendangnhap() !=null) {
			
		}
				if(yteToUpdate.getMatkhau() !=null) {
			
		}
		if (yteToUpdate.getRole() != null) {
			
		}
				if(yteToUpdate.getYtecol() !=null) {
			
		}
				return yteRepository.save(yte);
	}

	@Override
	public Boolean exist(Yte yte) {
						return yteRepository.existsById(yte.getIdyte());
																																																	}

	@Override
	public List<Yte> findAll() {
		return yteRepository.findAll();
	}

}


