/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 22:38:43 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;

import com.tlu.qlsuckhoe.entity.Yte;

import java.util.List;

public interface YteService {

	public Yte getOne(Integer idyte);

	public List<Yte> findAll();

	public Boolean delete(Integer idyte);

	public Yte create(Yte yte);

	public Yte update(Yte yte);

	public Boolean exist(Yte yte);
}
