/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.controller.test;
import static org.assertj.core.api.Assertions.assertThat;

import org.demo.controller.resource.ThietbiyteResource;
import com.tlu.qlsuckhoe.entity.Thietbiyte;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.hateoas.Link;
import org.springframework.hateoas.PagedResources;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.RequestEntity;
import org.springframework.http.ResponseEntity;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.test.context.jdbc.Sql.ExecutionPhase;
import org.springframework.test.context.jdbc.SqlGroup;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

// Junit specific runner
@RunWith(SpringJUnit4ClassRunner.class)
// Declare as spring boot test and define the port according to properties in
// src/test/resources/application.properties
@SpringBootTest(webEnvironment = WebEnvironment.DEFINED_PORT)
// Ensure all are clean between two method test execution
@SqlGroup({ @Sql(executionPhase = ExecutionPhase.BEFORE_TEST_METHOD, scripts = "classpath:clean.sql") })
public class ThietbiyteControllerTest {

	@Autowired
	private TestRestTemplate restTemplate;


	private static final Integer IDNHASANXUAT = Integer.valueOf(100);

	private static final String TENTHIETBI = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

	private static final Integer SOLUONG = Integer.valueOf(100);

	private static final String CACHDUNG = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

	@Test
	public void createThietbiyteTest() {
		// Create an thietbiyte
		Thietbiyte thietbiyte = createMocKThietbiyte(Integer.valueOf(100) , IDNHASANXUAT, TENTHIETBI, SOLUONG, CACHDUNG);
		// Recover this thietbiyte
		ResponseEntity<ThietbiyteResource> result = this.restTemplate.getForEntity("/thietbiyte/1", ThietbiyteResource.class);
		// The response can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		assertThat(result.getBody()).isNotNull();
		// Assert the Hateoas self link
		Link link = new Link("http://localhost:9999/thietbiyte/1", Link.REL_SELF);
		assertThat(result.getBody().getId()).isEqualTo(link);
		assertThat(result.getBody().getIdnhasanxuat()).isEqualTo(IDNHASANXUAT);
		assertThat(result.getBody().getTenthietbi()).isEqualTo(TENTHIETBI);
		assertThat(result.getBody().getSoluong()).isEqualTo(SOLUONG);
		assertThat(result.getBody().getCachdung()).isEqualTo(CACHDUNG);
		// Try to create the same thietbiyte, must return a CONFLICT status code
		result = this.restTemplate.postForEntity("/thietbiyte", thietbiyte, ThietbiyteResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.CONFLICT);
		// Response body must not be null
		assertThat(result.getBody()).isNull();
	}

	@Test
	public void updateTest() {
		// Create an thietbiyte and assert field
		Thietbiyte thietbiyte = createMocKThietbiyte(Integer.valueOf(100)  , IDNHASANXUAT, TENTHIETBI, SOLUONG, CACHDUNG);
		// Recover this thietbiyte
		ResponseEntity<ThietbiyteResource> result = this.restTemplate.getForEntity("/thietbiyte/1", ThietbiyteResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		assertThat(result.getBody()).isNotNull();
		// Assert the Hateoas self link
		Link link = new Link("http://localhost:9999/thietbiyte/1", Link.REL_SELF);
		assertThat(result.getBody().getId()).isEqualTo(link);
		assertThat(result.getBody().getIdnhasanxuat()).isEqualTo(IDNHASANXUAT);
		assertThat(result.getBody().getTenthietbi()).isEqualTo(TENTHIETBI);
		assertThat(result.getBody().getSoluong()).isEqualTo(SOLUONG);
		assertThat(result.getBody().getCachdung()).isEqualTo(CACHDUNG);

		// Change field value

		thietbiyte.setIdnhasanxuat(Integer.valueOf(200));

		thietbiyte.setTenthietbi("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB");

		thietbiyte.setSoluong(Integer.valueOf(200));

		thietbiyte.setCachdung("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB");
		// Process update
		RequestEntity<Thietbiyte> request = new RequestEntity<Thietbiyte>(thietbiyte, HttpMethod.PUT, null);
		ResponseEntity<Void> resultUpdate = this.restTemplate.exchange("/thietbiyte/1", HttpMethod.PUT, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultUpdate).isNotNull();
		// The status code must be OK
		assertThat(resultUpdate.getStatusCode()).isEqualTo(HttpStatus.OK);

		// Recover the thietbiyte and ensure field are correct
		result = this.restTemplate.getForEntity("/thietbiyte/1", ThietbiyteResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		assertThat(result.getBody()).isNotNull();
		// Assert the Hateoas self link
		link = new Link("http://localhost:9999/thietbiyte/1", Link.REL_SELF);
		assertThat(result.getBody().getId()).isEqualTo(link);

		assertThat(result.getBody().getIdnhasanxuat()).isEqualTo(Integer.valueOf(200));

		assertThat(result.getBody().getTenthietbi()).isEqualTo("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB");

		assertThat(result.getBody().getSoluong()).isEqualTo(Integer.valueOf(200));

		assertThat(result.getBody().getCachdung()).isEqualTo("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB");
	}

	@Test
	public void updateNotFoundTest() {
		// Process update
		RequestEntity<Thietbiyte> request = new RequestEntity<Thietbiyte>(new Thietbiyte(), HttpMethod.PUT, null);
		ResponseEntity<Void> resultUpdate = this.restTemplate.exchange("/thietbiyte/999", HttpMethod.PUT, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultUpdate).isNotNull();
		// The status code must be NOT_FOUND
		assertThat(resultUpdate.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
	}

	@Test
	public void deleteTest() {
		// Create an thietbiyte
		createMocKThietbiyte(Integer.valueOf(100)  , IDNHASANXUAT, TENTHIETBI, SOLUONG, CACHDUNG);
		// Recover this thietbiyte and test if all is ok
		ResponseEntity<ThietbiyteResource> result = this.restTemplate.getForEntity("/thietbiyte/1", ThietbiyteResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);

		// Delete the thietbiyte
		RequestEntity<Thietbiyte> request = new RequestEntity<Thietbiyte>(new Thietbiyte(), HttpMethod.DELETE, null);
		ResponseEntity<Void> resultDelete = this.restTemplate.exchange("/thietbiyte/1", HttpMethod.DELETE, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultDelete).isNotNull();
		// The status code must be NOT_CONTENT
		assertThat(resultDelete.getStatusCode()).isEqualTo(HttpStatus.NO_CONTENT);

		// Try to recover the thietbiyte and ensure it's don't exist
		// Recover this thietbiyte and test if all is ok
		result = this.restTemplate.getForEntity("/thietbiyte/1", ThietbiyteResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be NOT_FOUND
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
	}

	@Test
	public void deleteNotFound() {
		// Delete the thietbiyte
		RequestEntity<Thietbiyte> request = new RequestEntity<Thietbiyte>(new Thietbiyte(), HttpMethod.DELETE, null);
		ResponseEntity<Void> resultDelete = this.restTemplate.exchange("/thietbiyte/999", HttpMethod.DELETE, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultDelete).isNotNull();
		// The status code must be NOT_FOUND
		assertThat(resultDelete.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
	}

	@Test
	public void getThietbiytesTest() {
		// First call assert no element
		ResponseEntity<PagedResources<ThietbiyteResource>> result = this.search("/thietbiyte");
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		PagedResources<ThietbiyteResource> page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata()).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(0);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(0);
		// By default page size is 20
		assertThat(page.getMetadata().getSize()).isEqualTo(20);

		// Insert 21 thietbiyte
		for (int i = 1; i < 22; i++) {
			createMocKThietbiyte(new Integer((int)i),IDNHASANXUAT + i,String.valueOf(i),SOLUONG + i,String.valueOf(i));
		}
		result = this.search("/thietbiyte");
		// Response body must not be null
		page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(21);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(2);

		// Change the number of element per page and assert the page number
		result = this.search("/thietbiyte?size=3");
		// Response body must not be null
		page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(21);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(7);
	}

	@Test
	public void getThietbiytesTestFilter() {
		// Create an thietbiyte
		Thietbiyte thietbiyte = createMocKThietbiyte(Integer.valueOf(100) , IDNHASANXUAT, TENTHIETBI, SOLUONG, CACHDUNG);
		RequestEntity<Thietbiyte> request = null;
		ResponseEntity<PagedResources<ThietbiyteResource>> result = null;
		PagedResources<ThietbiyteResource> page = null;
		// Test tenthietbi filter
		// Set the value on entity and update
		thietbiyte.setTenthietbi("c");
		// Process update
		request = new RequestEntity<Thietbiyte>(thietbiyte, HttpMethod.PUT, null);
		this.restTemplate.exchange("/thietbiyte/1", HttpMethod.PUT, request, getTypeRefVoid());
		// Test tenthietbi filter
		result = this.search("/thietbiyte?size=20&tenthietbi=c");
		// Response body must not be null
		page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(1);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(1);
		for (ThietbiyteResource thietbiyteResource : page.getContent()) {
			assertThat(thietbiyteResource.getTenthietbi()).startsWith("c");
		}
		// Test cachdung filter
		// Set the value on entity and update
		thietbiyte.setCachdung("c");
		// Process update
		request = new RequestEntity<Thietbiyte>(thietbiyte, HttpMethod.PUT, null);
		this.restTemplate.exchange("/thietbiyte/1", HttpMethod.PUT, request, getTypeRefVoid());
		// Test cachdung filter
		result = this.search("/thietbiyte?size=20&cachdung=c");
		// Response body must not be null
		page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(1);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(1);
		for (ThietbiyteResource thietbiyteResource : page.getContent()) {
			assertThat(thietbiyteResource.getCachdung()).startsWith("c");
		}
	}

	private Thietbiyte createMocKThietbiyte(Integer idthietbiyte, Integer idnhasanxuat, String tenthietbi, Integer soluong, String cachdung) {
		Thietbiyte thietbiyteMock = new Thietbiyte();
		thietbiyteMock.setIdthietbiyte(idthietbiyte);
		thietbiyteMock.setIdnhasanxuat(idnhasanxuat);
		thietbiyteMock.setTenthietbi(tenthietbi);
		thietbiyteMock.setSoluong(soluong);
		thietbiyteMock.setCachdung(cachdung);
		this.restTemplate.postForLocation("/thietbiyte", thietbiyteMock);
		return thietbiyteMock;
	}

	private ResponseEntity<PagedResources<ThietbiyteResource>> search(String uri) {
		return this.restTemplate.exchange(uri, HttpMethod.GET, null, getTypeRef());
	}

	private ParameterizedTypeReference<PagedResources<ThietbiyteResource>> getTypeRef() {
		return new ParameterizedTypeReference<PagedResources<ThietbiyteResource>>() {
		};
	}

	private ParameterizedTypeReference<Void> getTypeRefVoid() {
		return new ParameterizedTypeReference<Void>() {
		};
	}
}