/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.controller.test;
import static org.assertj.core.api.Assertions.assertThat;

import org.demo.controller.resource.TintucResource;
import com.tlu.qlsuckhoe.entity.Tintuc;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.hateoas.Link;
import org.springframework.hateoas.PagedResources;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.RequestEntity;
import org.springframework.http.ResponseEntity;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.test.context.jdbc.Sql.ExecutionPhase;
import org.springframework.test.context.jdbc.SqlGroup;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

// Junit specific runner
@RunWith(SpringJUnit4ClassRunner.class)
// Declare as spring boot test and define the port according to properties in
// src/test/resources/application.properties
@SpringBootTest(webEnvironment = WebEnvironment.DEFINED_PORT)
// Ensure all are clean between two method test execution
@SqlGroup({ @Sql(executionPhase = ExecutionPhase.BEFORE_TEST_METHOD, scripts = "classpath:clean.sql") })
public class TintucControllerTest {

	@Autowired
	private TestRestTemplate restTemplate;


	private static final String TIEUDE = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

	private static final String NGAYDANG = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

	private static final String NOIDUNG = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

	@Test
	public void createTintucTest() {
		// Create an tintuc
		Tintuc tintuc = createMocKTintuc(Integer.valueOf(100) , TIEUDE, NGAYDANG, NOIDUNG);
		// Recover this tintuc
		ResponseEntity<TintucResource> result = this.restTemplate.getForEntity("/tintuc/1", TintucResource.class);
		// The response can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		assertThat(result.getBody()).isNotNull();
		// Assert the Hateoas self link
		Link link = new Link("http://localhost:9999/tintuc/1", Link.REL_SELF);
		assertThat(result.getBody().getId()).isEqualTo(link);
		assertThat(result.getBody().getTieude()).isEqualTo(TIEUDE);
		assertThat(result.getBody().getNgaydang()).isEqualTo(NGAYDANG);
		assertThat(result.getBody().getNoidung()).isEqualTo(NOIDUNG);
		// Try to create the same tintuc, must return a CONFLICT status code
		result = this.restTemplate.postForEntity("/tintuc", tintuc, TintucResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.CONFLICT);
		// Response body must not be null
		assertThat(result.getBody()).isNull();
	}

	@Test
	public void updateTest() {
		// Create an tintuc and assert field
		Tintuc tintuc = createMocKTintuc(Integer.valueOf(100)  , TIEUDE, NGAYDANG, NOIDUNG);
		// Recover this tintuc
		ResponseEntity<TintucResource> result = this.restTemplate.getForEntity("/tintuc/1", TintucResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		assertThat(result.getBody()).isNotNull();
		// Assert the Hateoas self link
		Link link = new Link("http://localhost:9999/tintuc/1", Link.REL_SELF);
		assertThat(result.getBody().getId()).isEqualTo(link);
		assertThat(result.getBody().getTieude()).isEqualTo(TIEUDE);
		assertThat(result.getBody().getNgaydang()).isEqualTo(NGAYDANG);
		assertThat(result.getBody().getNoidung()).isEqualTo(NOIDUNG);

		// Change field value

		tintuc.setTieude("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB");

		tintuc.setNgaydang("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB");

		tintuc.setNoidung("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB");
		// Process update
		RequestEntity<Tintuc> request = new RequestEntity<Tintuc>(tintuc, HttpMethod.PUT, null);
		ResponseEntity<Void> resultUpdate = this.restTemplate.exchange("/tintuc/1", HttpMethod.PUT, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultUpdate).isNotNull();
		// The status code must be OK
		assertThat(resultUpdate.getStatusCode()).isEqualTo(HttpStatus.OK);

		// Recover the tintuc and ensure field are correct
		result = this.restTemplate.getForEntity("/tintuc/1", TintucResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		assertThat(result.getBody()).isNotNull();
		// Assert the Hateoas self link
		link = new Link("http://localhost:9999/tintuc/1", Link.REL_SELF);
		assertThat(result.getBody().getId()).isEqualTo(link);

		assertThat(result.getBody().getTieude()).isEqualTo("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB");

		assertThat(result.getBody().getNgaydang()).isEqualTo("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB");

		assertThat(result.getBody().getNoidung()).isEqualTo("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB");
	}

	@Test
	public void updateNotFoundTest() {
		// Process update
		RequestEntity<Tintuc> request = new RequestEntity<Tintuc>(new Tintuc(), HttpMethod.PUT, null);
		ResponseEntity<Void> resultUpdate = this.restTemplate.exchange("/tintuc/999", HttpMethod.PUT, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultUpdate).isNotNull();
		// The status code must be NOT_FOUND
		assertThat(resultUpdate.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
	}

	@Test
	public void deleteTest() {
		// Create an tintuc
		createMocKTintuc(Integer.valueOf(100)  , TIEUDE, NGAYDANG, NOIDUNG);
		// Recover this tintuc and test if all is ok
		ResponseEntity<TintucResource> result = this.restTemplate.getForEntity("/tintuc/1", TintucResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);

		// Delete the tintuc
		RequestEntity<Tintuc> request = new RequestEntity<Tintuc>(new Tintuc(), HttpMethod.DELETE, null);
		ResponseEntity<Void> resultDelete = this.restTemplate.exchange("/tintuc/1", HttpMethod.DELETE, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultDelete).isNotNull();
		// The status code must be NOT_CONTENT
		assertThat(resultDelete.getStatusCode()).isEqualTo(HttpStatus.NO_CONTENT);

		// Try to recover the tintuc and ensure it's don't exist
		// Recover this tintuc and test if all is ok
		result = this.restTemplate.getForEntity("/tintuc/1", TintucResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be NOT_FOUND
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
	}

	@Test
	public void deleteNotFound() {
		// Delete the tintuc
		RequestEntity<Tintuc> request = new RequestEntity<Tintuc>(new Tintuc(), HttpMethod.DELETE, null);
		ResponseEntity<Void> resultDelete = this.restTemplate.exchange("/tintuc/999", HttpMethod.DELETE, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultDelete).isNotNull();
		// The status code must be NOT_FOUND
		assertThat(resultDelete.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
	}

	@Test
	public void getTintucsTest() {
		// First call assert no element
		ResponseEntity<PagedResources<TintucResource>> result = this.search("/tintuc");
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		PagedResources<TintucResource> page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata()).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(0);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(0);
		// By default page size is 20
		assertThat(page.getMetadata().getSize()).isEqualTo(20);

		// Insert 21 tintuc
		for (int i = 1; i < 22; i++) {
			createMocKTintuc(new Integer((int)i),String.valueOf(i),String.valueOf(i),String.valueOf(i));
		}
		result = this.search("/tintuc");
		// Response body must not be null
		page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(21);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(2);

		// Change the number of element per page and assert the page number
		result = this.search("/tintuc?size=3");
		// Response body must not be null
		page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(21);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(7);
	}

	@Test
	public void getTintucsTestFilter() {
		// Create an tintuc
		Tintuc tintuc = createMocKTintuc(Integer.valueOf(100) , TIEUDE, NGAYDANG, NOIDUNG);
		RequestEntity<Tintuc> request = null;
		ResponseEntity<PagedResources<TintucResource>> result = null;
		PagedResources<TintucResource> page = null;
		// Test tieude filter
		// Set the value on entity and update
		tintuc.setTieude("c");
		// Process update
		request = new RequestEntity<Tintuc>(tintuc, HttpMethod.PUT, null);
		this.restTemplate.exchange("/tintuc/1", HttpMethod.PUT, request, getTypeRefVoid());
		// Test tieude filter
		result = this.search("/tintuc?size=20&tieude=c");
		// Response body must not be null
		page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(1);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(1);
		for (TintucResource tintucResource : page.getContent()) {
			assertThat(tintucResource.getTieude()).startsWith("c");
		}
		// Test ngaydang filter
		// Set the value on entity and update
		tintuc.setNgaydang("c");
		// Process update
		request = new RequestEntity<Tintuc>(tintuc, HttpMethod.PUT, null);
		this.restTemplate.exchange("/tintuc/1", HttpMethod.PUT, request, getTypeRefVoid());
		// Test ngaydang filter
		result = this.search("/tintuc?size=20&ngaydang=c");
		// Response body must not be null
		page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(1);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(1);
		for (TintucResource tintucResource : page.getContent()) {
			assertThat(tintucResource.getNgaydang()).startsWith("c");
		}
		// Test noidung filter
		// Set the value on entity and update
		tintuc.setNoidung("c");
		// Process update
		request = new RequestEntity<Tintuc>(tintuc, HttpMethod.PUT, null);
		this.restTemplate.exchange("/tintuc/1", HttpMethod.PUT, request, getTypeRefVoid());
		// Test noidung filter
		result = this.search("/tintuc?size=20&noidung=c");
		// Response body must not be null
		page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(1);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(1);
		for (TintucResource tintucResource : page.getContent()) {
			assertThat(tintucResource.getNoidung()).startsWith("c");
		}
	}

	private Tintuc createMocKTintuc(Integer idtintuc, String tieude, String ngaydang, String noidung) {
		Tintuc tintucMock = new Tintuc();
		tintucMock.setIdtintuc(idtintuc);
		tintucMock.setTieude(tieude);
		tintucMock.setNgaydang(ngaydang);
		tintucMock.setNoidung(noidung);
		this.restTemplate.postForLocation("/tintuc", tintucMock);
		return tintucMock;
	}

	private ResponseEntity<PagedResources<TintucResource>> search(String uri) {
		return this.restTemplate.exchange(uri, HttpMethod.GET, null, getTypeRef());
	}

	private ParameterizedTypeReference<PagedResources<TintucResource>> getTypeRef() {
		return new ParameterizedTypeReference<PagedResources<TintucResource>>() {
		};
	}

	private ParameterizedTypeReference<Void> getTypeRefVoid() {
		return new ParameterizedTypeReference<Void>() {
		};
	}
}