/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:53 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for Admin entity stored in table admin.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="admin", catalog="qlsuckhoe" )
public class Admin implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="idadmin", nullable=false)
    private Integer idadmin ; 
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="tendangnhap", length=45)
    private String tendangnhap ;     @Column(name="matkhau", length=45)
    private String matkhau ;     @Column(name="idrole")
    private Integer idrole ; // Foreign Key 

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Admin() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setIdadmin(Integer idadmin) {
        this.idadmin = idadmin ;
    }
	public Integer getIdadmin() {
        return this.idadmin;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : tendangnhap (VARCHAR) 
	public void setTendangnhap(String tendangnhap) {this.tendangnhap = tendangnhap;}
	public String getTendangnhap() {return this.tendangnhap;}

	//--- DATABASE MAPPING : matkhau (VARCHAR) 
	public void setMatkhau(String matkhau) {this.matkhau = matkhau;}
	public String getMatkhau() {return this.matkhau;}

	//--- DATABASE MAPPING : idrole (INT) 
	public void setIdrole(Integer idrole) {this.idrole = idrole;}
	public Integer getIdrole() {return this.idrole;}


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(idadmin); 
		sb.append(tendangnhap); 
		sb.append("|"); 
		sb.append(matkhau); 
		sb.append("|"); 
		sb.append(idrole); 
        return sb.toString();
    }
}