/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:53 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for Benh entity stored in table benh.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="benh", catalog="qlsuckhoe" )
public class Benh implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="idbenh", nullable=false)
    private Integer idbenh ; 
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="iddanhmuc")
    private Integer iddanhmuc ;     @Column(name="tenbenh", length=45)
    private String tenbenh ;     @Column(name="trieuchung", length=100)
    private String trieuchung ;     @Column(name="cachchua", length=100)
    private String cachchua ; 

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Benh() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setIdbenh(Integer idbenh) {
        this.idbenh = idbenh ;
    }
	public Integer getIdbenh() {
        return this.idbenh;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : iddanhmuc (INT) 
	public void setIddanhmuc(Integer iddanhmuc) {this.iddanhmuc = iddanhmuc;}
	public Integer getIddanhmuc() {return this.iddanhmuc;}

	//--- DATABASE MAPPING : tenbenh (VARCHAR) 
	public void setTenbenh(String tenbenh) {this.tenbenh = tenbenh;}
	public String getTenbenh() {return this.tenbenh;}

	//--- DATABASE MAPPING : trieuchung (VARCHAR) 
	public void setTrieuchung(String trieuchung) {this.trieuchung = trieuchung;}
	public String getTrieuchung() {return this.trieuchung;}

	//--- DATABASE MAPPING : cachchua (VARCHAR) 
	public void setCachchua(String cachchua) {this.cachchua = cachchua;}
	public String getCachchua() {return this.cachchua;}


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(idbenh); 
		sb.append(iddanhmuc); 
		sb.append("|"); 
		sb.append(tenbenh); 
		sb.append("|"); 
		sb.append(trieuchung); 
		sb.append("|"); 
		sb.append(cachchua); 
        return sb.toString();
    }
}