package com.tlu.qlsuckhoe.entity;
// Generated Oct 1, 2018 10:37:59 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Benh generated by hbm2java
 */
@Entity
@Table(name = "benh", catalog = "qlsuckhoe")
public class Benh implements java.io.Serializable {

	private Integer idbenh;
	private Integer iddanhmuc;
	private String tenbenh;
	private String trieuchung;
	private String cachchua;
	private Set<Dinhky> dinhkies = new HashSet<Dinhky>(0);

	public Benh() {
	}

	public Benh(Integer iddanhmuc, String tenbenh, String trieuchung, String cachchua, Set<Dinhky> dinhkies) {
		this.iddanhmuc = iddanhmuc;
		this.tenbenh = tenbenh;
		this.trieuchung = trieuchung;
		this.cachchua = cachchua;
		this.dinhkies = dinhkies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idbenh", unique = true, nullable = false)
	public Integer getIdbenh() {
		return this.idbenh;
	}

	public void setIdbenh(Integer idbenh) {
		this.idbenh = idbenh;
	}

	@Column(name = "iddanhmuc")
	public Integer getIddanhmuc() {
		return this.iddanhmuc;
	}

	public void setIddanhmuc(Integer iddanhmuc) {
		this.iddanhmuc = iddanhmuc;
	}

	@Column(name = "tenbenh", length = 45)
	public String getTenbenh() {
		return this.tenbenh;
	}

	public void setTenbenh(String tenbenh) {
		this.tenbenh = tenbenh;
	}

	@Column(name = "trieuchung", length = 100)
	public String getTrieuchung() {
		return this.trieuchung;
	}

	public void setTrieuchung(String trieuchung) {
		this.trieuchung = trieuchung;
	}

	@Column(name = "cachchua", length = 100)
	public String getCachchua() {
		return this.cachchua;
	}

	public void setCachchua(String cachchua) {
		this.cachchua = cachchua;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "benh")
	public Set<Dinhky> getDinhkies() {
		return this.dinhkies;
	}

	public void setDinhkies(Set<Dinhky> dinhkies) {
		this.dinhkies = dinhkies;
	}

}
