/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for Danhmuc entity stored in table danhmuc.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="danhmuc", catalog="qlsuckhoe" )
public class Danhmuc implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="iddanhmuc", nullable=false)
    private Integer iddanhmuc ; 
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="tendanhmuc", length=45)
    private String tendanhmuc ; 

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Danhmuc() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setIddanhmuc(Integer iddanhmuc) {
        this.iddanhmuc = iddanhmuc ;
    }
	public Integer getIddanhmuc() {
        return this.iddanhmuc;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : tendanhmuc (VARCHAR) 
	public void setTendanhmuc(String tendanhmuc) {this.tendanhmuc = tendanhmuc;}
	public String getTendanhmuc() {return this.tendanhmuc;}


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(iddanhmuc); 
		sb.append(tendanhmuc); 
        return sb.toString();
    }
}