/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for Dinhky entity stored in table dinhky.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="dinhky", catalog="qlsuckhoe" )
public class Dinhky implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="idkhamdinhky", nullable=false)
    private Integer idkhamdinhky ; 
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="idsinhvien")
    private Integer idsinhvien ; // Foreign Key     @Column(name="idhocki")
    private Integer idhocki ; // Foreign Key     @Column(name="idbenh")
    private Integer idbenh ; // Foreign Key     @Column(name="chieucao", length=45)
    private String chieucao ;     @Column(name="cannang", length=45)
    private String cannang ;     @Column(name="huyetap", length=45)
    private String huyetap ;     @Column(name="loaisuckhoe", length=45)
    private String loaisuckhoe ;     @Column(name="ketluan", length=45)
    private String ketluan ;     @Column(name="chuandoan", length=45)
    private String chuandoan ; 

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Dinhky() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setIdkhamdinhky(Integer idkhamdinhky) {
        this.idkhamdinhky = idkhamdinhky ;
    }
	public Integer getIdkhamdinhky() {
        return this.idkhamdinhky;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : idsinhvien (INT) 
	public void setIdsinhvien(Integer idsinhvien) {this.idsinhvien = idsinhvien;}
	public Integer getIdsinhvien() {return this.idsinhvien;}

	//--- DATABASE MAPPING : idhocki (INT) 
	public void setIdhocki(Integer idhocki) {this.idhocki = idhocki;}
	public Integer getIdhocki() {return this.idhocki;}

	//--- DATABASE MAPPING : idbenh (INT) 
	public void setIdbenh(Integer idbenh) {this.idbenh = idbenh;}
	public Integer getIdbenh() {return this.idbenh;}

	//--- DATABASE MAPPING : chieucao (VARCHAR) 
	public void setChieucao(String chieucao) {this.chieucao = chieucao;}
	public String getChieucao() {return this.chieucao;}

	//--- DATABASE MAPPING : cannang (VARCHAR) 
	public void setCannang(String cannang) {this.cannang = cannang;}
	public String getCannang() {return this.cannang;}

	//--- DATABASE MAPPING : huyetap (VARCHAR) 
	public void setHuyetap(String huyetap) {this.huyetap = huyetap;}
	public String getHuyetap() {return this.huyetap;}

	//--- DATABASE MAPPING : loaisuckhoe (VARCHAR) 
	public void setLoaisuckhoe(String loaisuckhoe) {this.loaisuckhoe = loaisuckhoe;}
	public String getLoaisuckhoe() {return this.loaisuckhoe;}

	//--- DATABASE MAPPING : ketluan (VARCHAR) 
	public void setKetluan(String ketluan) {this.ketluan = ketluan;}
	public String getKetluan() {return this.ketluan;}

	//--- DATABASE MAPPING : chuandoan (VARCHAR) 
	public void setChuandoan(String chuandoan) {this.chuandoan = chuandoan;}
	public String getChuandoan() {return this.chuandoan;}


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(idkhamdinhky); 
		sb.append(idsinhvien); 
		sb.append("|"); 
		sb.append(idhocki); 
		sb.append("|"); 
		sb.append(idbenh); 
		sb.append("|"); 
		sb.append(chieucao); 
		sb.append("|"); 
		sb.append(cannang); 
		sb.append("|"); 
		sb.append(huyetap); 
		sb.append("|"); 
		sb.append(loaisuckhoe); 
		sb.append("|"); 
		sb.append(ketluan); 
		sb.append("|"); 
		sb.append(chuandoan); 
        return sb.toString();
    }
}