package com.tlu.qlsuckhoe.entity;
// Generated Oct 1, 2018 10:37:59 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Dinhky generated by hbm2java
 */
@Entity
@Table(name = "dinhky", catalog = "qlsuckhoe")
public class Dinhky implements java.io.Serializable {

	private Integer idkhamdinhky;
	private Benh benh;
	private Hocki hocki;
	private Sinhvien sinhvien;
	private String chieucao;
	private String cannang;
	private String huyetap;
	private String loaisuckhoe;
	private String ketluan;
	private String chuandoan;

	public Dinhky() {
	}

	public Dinhky(Benh benh, Hocki hocki, Sinhvien sinhvien, String chieucao, String cannang, String huyetap,
				  String loaisuckhoe, String ketluan, String chuandoan) {
		this.benh = benh;
		this.hocki = hocki;
		this.sinhvien = sinhvien;
		this.chieucao = chieucao;
		this.cannang = cannang;
		this.huyetap = huyetap;
		this.loaisuckhoe = loaisuckhoe;
		this.ketluan = ketluan;
		this.chuandoan = chuandoan;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idkhamdinhky", unique = true, nullable = false)
	public Integer getIdkhamdinhky() {
		return this.idkhamdinhky;
	}

	public void setIdkhamdinhky(Integer idkhamdinhky) {
		this.idkhamdinhky = idkhamdinhky;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idbenh")
	public Benh getBenh() {
		return this.benh;
	}

	public void setBenh(Benh benh) {
		this.benh = benh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idhocki")
	public Hocki getHocki() {
		return this.hocki;
	}

	public void setHocki(Hocki hocki) {
		this.hocki = hocki;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idsinhvien")
	public Sinhvien getSinhvien() {
		return this.sinhvien;
	}

	public void setSinhvien(Sinhvien sinhvien) {
		this.sinhvien = sinhvien;
	}

	@Column(name = "chieucao", length = 45)
	public String getChieucao() {
		return this.chieucao;
	}

	public void setChieucao(String chieucao) {
		this.chieucao = chieucao;
	}

	@Column(name = "cannang", length = 45)
	public String getCannang() {
		return this.cannang;
	}

	public void setCannang(String cannang) {
		this.cannang = cannang;
	}

	@Column(name = "huyetap", length = 45)
	public String getHuyetap() {
		return this.huyetap;
	}

	public void setHuyetap(String huyetap) {
		this.huyetap = huyetap;
	}

	@Column(name = "loaisuckhoe", length = 45)
	public String getLoaisuckhoe() {
		return this.loaisuckhoe;
	}

	public void setLoaisuckhoe(String loaisuckhoe) {
		this.loaisuckhoe = loaisuckhoe;
	}

	@Column(name = "ketluan", length = 45)
	public String getKetluan() {
		return this.ketluan;
	}

	public void setKetluan(String ketluan) {
		this.ketluan = ketluan;
	}

	@Column(name = "chuandoan", length = 45)
	public String getChuandoan() {
		return this.chuandoan;
	}

	public void setChuandoan(String chuandoan) {
		this.chuandoan = chuandoan;
	}

}
