package com.tlu.qlsuckhoe.entity;
// Generated Oct 1, 2018 10:37:59 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Hocki generated by hbm2java
 */
@Entity
@Table(name = "hocki", catalog = "qlsuckhoe")
public class Hocki implements java.io.Serializable {

	private Integer idhocki;
	private String tenhocki;
	private Set<Dinhky> dinhkies = new HashSet<Dinhky>(0);

	public Hocki() {
	}

	public Hocki(String tenhocki, Set<Dinhky> dinhkies) {
		this.tenhocki = tenhocki;
		this.dinhkies = dinhkies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idhocki", unique = true, nullable = false)
	public Integer getIdhocki() {
		return this.idhocki;
	}

	public void setIdhocki(Integer idhocki) {
		this.idhocki = idhocki;
	}

	@Column(name = "tenhocki", length = 45)
	public String getTenhocki() {
		return this.tenhocki;
	}

	public void setTenhocki(String tenhocki) {
		this.tenhocki = tenhocki;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hocki")
	public Set<Dinhky> getDinhkies() {
		return this.dinhkies;
	}

	public void setDinhkies(Set<Dinhky> dinhkies) {
		this.dinhkies = dinhkies;
	}

}
