package com.tlu.qlsuckhoe.entity;
// Generated Oct 1, 2018 10:37:59 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "qlsuckhoe")
public class Role implements java.io.Serializable {

	private int idrole;
	private String name;
	private Set<Admin> admins = new HashSet<Admin>(0);
	private Set<Yte> ytes = new HashSet<Yte>(0);
	private Set<Sinhvien> sinhviens = new HashSet<Sinhvien>(0);

	public Role() {
	}

	public Role(int idrole) {
		this.idrole = idrole;
	}

	public Role(int idrole, String name, Set<Admin> admins, Set<Yte> ytes, Set<Sinhvien> sinhviens) {
		this.idrole = idrole;
		this.name = name;
		this.admins = admins;
		this.ytes = ytes;
		this.sinhviens = sinhviens;
	}

	@Id

	@Column(name = "idrole", unique = true, nullable = false)
	public int getIdrole() {
		return this.idrole;
	}

	public void setIdrole(int idrole) {
		this.idrole = idrole;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<Admin> getAdmins() {
		return this.admins;
	}

	public void setAdmins(Set<Admin> admins) {
		this.admins = admins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<Yte> getYtes() {
		return this.ytes;
	}

	public void setYtes(Set<Yte> ytes) {
		this.ytes = ytes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<Sinhvien> getSinhviens() {
		return this.sinhviens;
	}

	public void setSinhviens(Set<Sinhvien> sinhviens) {
		this.sinhviens = sinhviens;
	}

}
