/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for Sinhvien entity stored in table sinhvien.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="sinhvien", catalog="qlsuckhoe" )
public class Sinhvien implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="idsinhvien", nullable=false)
    private Integer idsinhvien ; 
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="hoten", length=45)
    private String hoten ;     @Column(name="gioitinh", length=45)
    private String gioitinh ;     @Column(name="namsinh", length=45)
    private String namsinh ;     @Column(name="socmt", length=45)
    private String socmt ;     @Column(name="diachi", length=45)
    private String diachi ;     @Column(name="chuyennganh", length=45)
    private String chuyennganh ;     @Column(name="khoa", length=45)
    private String khoa ;     @Column(name="masv", length=45)
    private String masv ;     @Column(name="matkhau", length=45)
    private String matkhau ;     @Column(name="idrole")
    private Integer idrole ; // Foreign Key 

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Sinhvien() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setIdsinhvien(Integer idsinhvien) {
        this.idsinhvien = idsinhvien ;
    }
	public Integer getIdsinhvien() {
        return this.idsinhvien;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : hoten (VARCHAR) 
	public void setHoten(String hoten) {this.hoten = hoten;}
	public String getHoten() {return this.hoten;}

	//--- DATABASE MAPPING : gioitinh (VARCHAR) 
	public void setGioitinh(String gioitinh) {this.gioitinh = gioitinh;}
	public String getGioitinh() {return this.gioitinh;}

	//--- DATABASE MAPPING : namsinh (VARCHAR) 
	public void setNamsinh(String namsinh) {this.namsinh = namsinh;}
	public String getNamsinh() {return this.namsinh;}

	//--- DATABASE MAPPING : socmt (VARCHAR) 
	public void setSocmt(String socmt) {this.socmt = socmt;}
	public String getSocmt() {return this.socmt;}

	//--- DATABASE MAPPING : diachi (VARCHAR) 
	public void setDiachi(String diachi) {this.diachi = diachi;}
	public String getDiachi() {return this.diachi;}

	//--- DATABASE MAPPING : chuyennganh (VARCHAR) 
	public void setChuyennganh(String chuyennganh) {this.chuyennganh = chuyennganh;}
	public String getChuyennganh() {return this.chuyennganh;}

	//--- DATABASE MAPPING : khoa (VARCHAR) 
	public void setKhoa(String khoa) {this.khoa = khoa;}
	public String getKhoa() {return this.khoa;}

	//--- DATABASE MAPPING : masv (VARCHAR) 
	public void setMasv(String masv) {this.masv = masv;}
	public String getMasv() {return this.masv;}

	//--- DATABASE MAPPING : matkhau (VARCHAR) 
	public void setMatkhau(String matkhau) {this.matkhau = matkhau;}
	public String getMatkhau() {return this.matkhau;}

	//--- DATABASE MAPPING : idrole (INT) 
	public void setIdrole(Integer idrole) {this.idrole = idrole;}
	public Integer getIdrole() {return this.idrole;}


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(idsinhvien); 
		sb.append(hoten); 
		sb.append("|"); 
		sb.append(gioitinh); 
		sb.append("|"); 
		sb.append(namsinh); 
		sb.append("|"); 
		sb.append(socmt); 
		sb.append("|"); 
		sb.append(diachi); 
		sb.append("|"); 
		sb.append(chuyennganh); 
		sb.append("|"); 
		sb.append(khoa); 
		sb.append("|"); 
		sb.append(masv); 
		sb.append("|"); 
		sb.append(matkhau); 
		sb.append("|"); 
		sb.append(idrole); 
        return sb.toString();
    }
}