package com.tlu.qlsuckhoe.entity;
// Generated Oct 1, 2018 10:37:59 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Sinhvien generated by hbm2java
 */
@Entity
@Table(name = "sinhvien", catalog = "qlsuckhoe")
public class Sinhvien implements java.io.Serializable {

	private Integer idsinhvien;
	private Role role;
	private String hoten;
	private String gioitinh;
	private String namsinh;
	private String socmt;
	private String diachi;
	private String chuyennganh;
	private String khoa;
	private String masv;
	private String matkhau;
	private Set<Dinhky> dinhkies = new HashSet<Dinhky>(0);
	private Set<Sucosuckhoe> sucosuckhoes = new HashSet<Sucosuckhoe>(0);

	public Sinhvien() {
	}

	public Sinhvien(Role role, String hoten, String gioitinh, String namsinh, String socmt, String diachi,
					String chuyennganh, String khoa, String masv, String matkhau, Set<Dinhky> dinhkies,
					Set<Sucosuckhoe> sucosuckhoes) {
		this.role = role;
		this.hoten = hoten;
		this.gioitinh = gioitinh;
		this.namsinh = namsinh;
		this.socmt = socmt;
		this.diachi = diachi;
		this.chuyennganh = chuyennganh;
		this.khoa = khoa;
		this.masv = masv;
		this.matkhau = matkhau;
		this.dinhkies = dinhkies;
		this.sucosuckhoes = sucosuckhoes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idsinhvien", unique = true, nullable = false)
	public Integer getIdsinhvien() {
		return this.idsinhvien;
	}

	public void setIdsinhvien(Integer idsinhvien) {
		this.idsinhvien = idsinhvien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idrole")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "hoten", length = 45)
	public String getHoten() {
		return this.hoten;
	}

	public void setHoten(String hoten) {
		this.hoten = hoten;
	}

	@Column(name = "gioitinh", length = 45)
	public String getGioitinh() {
		return this.gioitinh;
	}

	public void setGioitinh(String gioitinh) {
		this.gioitinh = gioitinh;
	}

	@Column(name = "namsinh", length = 45)
	public String getNamsinh() {
		return this.namsinh;
	}

	public void setNamsinh(String namsinh) {
		this.namsinh = namsinh;
	}

	@Column(name = "socmt", length = 45)
	public String getSocmt() {
		return this.socmt;
	}

	public void setSocmt(String socmt) {
		this.socmt = socmt;
	}

	@Column(name = "diachi", length = 45)
	public String getDiachi() {
		return this.diachi;
	}

	public void setDiachi(String diachi) {
		this.diachi = diachi;
	}

	@Column(name = "chuyennganh", length = 45)
	public String getChuyennganh() {
		return this.chuyennganh;
	}

	public void setChuyennganh(String chuyennganh) {
		this.chuyennganh = chuyennganh;
	}

	@Column(name = "khoa", length = 45)
	public String getKhoa() {
		return this.khoa;
	}

	public void setKhoa(String khoa) {
		this.khoa = khoa;
	}

	@Column(name = "masv", length = 45)
	public String getMasv() {
		return this.masv;
	}

	public void setMasv(String masv) {
		this.masv = masv;
	}

	@Column(name = "matkhau", length = 45)
	public String getMatkhau() {
		return this.matkhau;
	}

	public void setMatkhau(String matkhau) {
		this.matkhau = matkhau;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sinhvien")
	public Set<Dinhky> getDinhkies() {
		return this.dinhkies;
	}

	public void setDinhkies(Set<Dinhky> dinhkies) {
		this.dinhkies = dinhkies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sinhvien")
	public Set<Sucosuckhoe> getSucosuckhoes() {
		return this.sucosuckhoes;
	}

	public void setSucosuckhoes(Set<Sucosuckhoe> sucosuckhoes) {
		this.sucosuckhoes = sucosuckhoes;
	}

}
