package com.tlu.qlsuckhoe.entity;
// Generated Oct 1, 2018 10:37:59 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Sucosuckhoe generated by hbm2java
 */
@Entity
@Table(name = "sucosuckhoe", catalog = "qlsuckhoe")
public class Sucosuckhoe implements java.io.Serializable {

	private Integer idsucosuckhoe;
	private Sinhvien sinhvien;
	private Thuoc thuoc;
	private String ngay;
	private String loaisuco;
	private String bienphap;
	private String mucdo;
	private String nguoixuly;
	private Integer idthietbiyte;

	public Sucosuckhoe() {
	}

	public Sucosuckhoe(Sinhvien sinhvien, Thuoc thuoc, String ngay, String loaisuco, String bienphap, String mucdo,
					   String nguoixuly, Integer idthietbiyte) {
		this.sinhvien = sinhvien;
		this.thuoc = thuoc;
		this.ngay = ngay;
		this.loaisuco = loaisuco;
		this.bienphap = bienphap;
		this.mucdo = mucdo;
		this.nguoixuly = nguoixuly;
		this.idthietbiyte = idthietbiyte;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idsucosuckhoe", unique = true, nullable = false)
	public Integer getIdsucosuckhoe() {
		return this.idsucosuckhoe;
	}

	public void setIdsucosuckhoe(Integer idsucosuckhoe) {
		this.idsucosuckhoe = idsucosuckhoe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idsinhvien")
	public Sinhvien getSinhvien() {
		return this.sinhvien;
	}

	public void setSinhvien(Sinhvien sinhvien) {
		this.sinhvien = sinhvien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idthuoc")
	public Thuoc getThuoc() {
		return this.thuoc;
	}

	public void setThuoc(Thuoc thuoc) {
		this.thuoc = thuoc;
	}

	@Column(name = "ngay", length = 45)
	public String getNgay() {
		return this.ngay;
	}

	public void setNgay(String ngay) {
		this.ngay = ngay;
	}

	@Column(name = "loaisuco", length = 45)
	public String getLoaisuco() {
		return this.loaisuco;
	}

	public void setLoaisuco(String loaisuco) {
		this.loaisuco = loaisuco;
	}

	@Column(name = "bienphap", length = 45)
	public String getBienphap() {
		return this.bienphap;
	}

	public void setBienphap(String bienphap) {
		this.bienphap = bienphap;
	}

	@Column(name = "mucdo", length = 45)
	public String getMucdo() {
		return this.mucdo;
	}

	public void setMucdo(String mucdo) {
		this.mucdo = mucdo;
	}

	@Column(name = "nguoixuly", length = 45)
	public String getNguoixuly() {
		return this.nguoixuly;
	}

	public void setNguoixuly(String nguoixuly) {
		this.nguoixuly = nguoixuly;
	}

	@Column(name = "idthietbiyte")
	public Integer getIdthietbiyte() {
		return this.idthietbiyte;
	}

	public void setIdthietbiyte(Integer idthietbiyte) {
		this.idthietbiyte = idthietbiyte;
	}

}
