package com.tlu.qlsuckhoe.entity;
// Generated Oct 1, 2018 10:37:59 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Thietbiyte generated by hbm2java
 */
@Entity
@Table(name = "thietbiyte", catalog = "qlsuckhoe")
public class Thietbiyte implements java.io.Serializable {

	private Integer idthietbiyte;
	private Nhasanxuat nhasanxuat;
	private String tenthietbi;
	private Integer soluong;
	private String cachdung;

	public Thietbiyte() {
	}

	public Thietbiyte(Nhasanxuat nhasanxuat, String tenthietbi, Integer soluong, String cachdung) {
		this.nhasanxuat = nhasanxuat;
		this.tenthietbi = tenthietbi;
		this.soluong = soluong;
		this.cachdung = cachdung;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idthietbiyte", unique = true, nullable = false)
	public Integer getIdthietbiyte() {
		return this.idthietbiyte;
	}

	public void setIdthietbiyte(Integer idthietbiyte) {
		this.idthietbiyte = idthietbiyte;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idnhasanxuat")
	public Nhasanxuat getNhasanxuat() {
		return this.nhasanxuat;
	}

	public void setNhasanxuat(Nhasanxuat nhasanxuat) {
		this.nhasanxuat = nhasanxuat;
	}

	@Column(name = "tenthietbi", length = 45)
	public String getTenthietbi() {
		return this.tenthietbi;
	}

	public void setTenthietbi(String tenthietbi) {
		this.tenthietbi = tenthietbi;
	}

	@Column(name = "soluong")
	public Integer getSoluong() {
		return this.soluong;
	}

	public void setSoluong(Integer soluong) {
		this.soluong = soluong;
	}

	@Column(name = "cachdung", length = 45)
	public String getCachdung() {
		return this.cachdung;
	}

	public void setCachdung(String cachdung) {
		this.cachdung = cachdung;
	}

}
