package com.tlu.qlsuckhoe.entity;
// Generated Oct 1, 2018 10:37:59 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Thuoc generated by hbm2java
 */
@Entity
@Table(name = "thuoc", catalog = "qlsuckhoe")
public class Thuoc implements java.io.Serializable {

	private Integer idthuoc;
	private Loaithuoc loaithuoc;
	private Nhasanxuat nhasanxuat;
	private String tenthuoc;
	private String tacdung;
	private String cachdung;
	private String ngaynhap;
	private Integer soluong;
	private Set<Sucosuckhoe> sucosuckhoes = new HashSet<Sucosuckhoe>(0);

	public Thuoc() {
	}

	public Thuoc(Loaithuoc loaithuoc, Nhasanxuat nhasanxuat, String tenthuoc, String tacdung, String cachdung,
				 String ngaynhap, Integer soluong, Set<Sucosuckhoe> sucosuckhoes) {
		this.loaithuoc = loaithuoc;
		this.nhasanxuat = nhasanxuat;
		this.tenthuoc = tenthuoc;
		this.tacdung = tacdung;
		this.cachdung = cachdung;
		this.ngaynhap = ngaynhap;
		this.soluong = soluong;
		this.sucosuckhoes = sucosuckhoes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idthuoc", unique = true, nullable = false)
	public Integer getIdthuoc() {
		return this.idthuoc;
	}

	public void setIdthuoc(Integer idthuoc) {
		this.idthuoc = idthuoc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idloaithuoc")
	public Loaithuoc getLoaithuoc() {
		return this.loaithuoc;
	}

	public void setLoaithuoc(Loaithuoc loaithuoc) {
		this.loaithuoc = loaithuoc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idnhasanxuat")
	public Nhasanxuat getNhasanxuat() {
		return this.nhasanxuat;
	}

	public void setNhasanxuat(Nhasanxuat nhasanxuat) {
		this.nhasanxuat = nhasanxuat;
	}

	@Column(name = "tenthuoc", length = 45)
	public String getTenthuoc() {
		return this.tenthuoc;
	}

	public void setTenthuoc(String tenthuoc) {
		this.tenthuoc = tenthuoc;
	}

	@Column(name = "tacdung", length = 45)
	public String getTacdung() {
		return this.tacdung;
	}

	public void setTacdung(String tacdung) {
		this.tacdung = tacdung;
	}

	@Column(name = "cachdung", length = 45)
	public String getCachdung() {
		return this.cachdung;
	}

	public void setCachdung(String cachdung) {
		this.cachdung = cachdung;
	}

	@Column(name = "ngaynhap", length = 45)
	public String getNgaynhap() {
		return this.ngaynhap;
	}

	public void setNgaynhap(String ngaynhap) {
		this.ngaynhap = ngaynhap;
	}

	@Column(name = "soluong")
	public Integer getSoluong() {
		return this.soluong;
	}

	public void setSoluong(Integer soluong) {
		this.soluong = soluong;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "thuoc")
	public Set<Sucosuckhoe> getSucosuckhoes() {
		return this.sucosuckhoes;
	}

	public void setSucosuckhoes(Set<Sucosuckhoe> sucosuckhoes) {
		this.sucosuckhoes = sucosuckhoes;
	}

}
