package com.tlu.qlsuckhoe.entity;
// Generated Oct 1, 2018 10:37:59 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Tintuc generated by hbm2java
 */
@Entity
@Table(name = "tintuc", catalog = "qlsuckhoe")
public class Tintuc implements java.io.Serializable {

	private Integer idtintuc;
	private String tieude;
	private String ngaydang;
	private String noidung;

	public Tintuc() {
	}

	public Tintuc(String tieude, String ngaydang, String noidung) {
		this.tieude = tieude;
		this.ngaydang = ngaydang;
		this.noidung = noidung;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idtintuc", unique = true, nullable = false)
	public Integer getIdtintuc() {
		return this.idtintuc;
	}

	public void setIdtintuc(Integer idtintuc) {
		this.idtintuc = idtintuc;
	}

	@Column(name = "tieude", length = 45)
	public String getTieude() {
		return this.tieude;
	}

	public void setTieude(String tieude) {
		this.tieude = tieude;
	}

	@Column(name = "ngaydang", length = 45)
	public String getNgaydang() {
		return this.ngaydang;
	}

	public void setNgaydang(String ngaydang) {
		this.ngaydang = ngaydang;
	}

	@Column(name = "noidung", length = 45)
	public String getNoidung() {
		return this.noidung;
	}

	public void setNoidung(String noidung) {
		this.noidung = noidung;
	}

}
