/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for Tintuc entity stored in table tintuc.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="tintuc", catalog="qlsuckhoe" )
public class Tintuc implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="idtintuc", nullable=false)
    private Integer idtintuc ; 
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="tieude", length=45)
    private String tieude ;     @Column(name="ngaydang", length=45)
    private String ngaydang ;     @Column(name="noidung", length=45)
    private String noidung ; 

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Tintuc() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setIdtintuc(Integer idtintuc) {
        this.idtintuc = idtintuc ;
    }
	public Integer getIdtintuc() {
        return this.idtintuc;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : tieude (VARCHAR) 
	public void setTieude(String tieude) {this.tieude = tieude;}
	public String getTieude() {return this.tieude;}

	//--- DATABASE MAPPING : ngaydang (VARCHAR) 
	public void setNgaydang(String ngaydang) {this.ngaydang = ngaydang;}
	public String getNgaydang() {return this.ngaydang;}

	//--- DATABASE MAPPING : noidung (VARCHAR) 
	public void setNoidung(String noidung) {this.noidung = noidung;}
	public String getNoidung() {return this.noidung;}


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(idtintuc); 
		sb.append(tieude); 
		sb.append("|"); 
		sb.append(ngaydang); 
		sb.append("|"); 
		sb.append(noidung); 
        return sb.toString();
    }
}