package com.tlu.qlsuckhoe.entity;
// Generated Oct 1, 2018 10:37:59 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Yte generated by hbm2java
 */
@Entity
@Table(name = "yte", catalog = "qlsuckhoe")
public class Yte implements java.io.Serializable {

	private Integer idyte;
	private Role role;
	private String hoten;
	private String gioitinh;
	private String namsinh;
	private String diachi;
	private String socmt;
	private String sodt;
	private String chucvu;
	private String tendangnhap;
	private String matkhau;
	private String ytecol;

	public Yte() {
	}

	public Yte(String ytecol) {
		this.ytecol = ytecol;
	}

	public Yte(Role role, String hoten, String gioitinh, String namsinh, String diachi, String socmt, String sodt,
			   String chucvu, String tendangnhap, String matkhau, String ytecol) {
		this.role = role;
		this.hoten = hoten;
		this.gioitinh = gioitinh;
		this.namsinh = namsinh;
		this.diachi = diachi;
		this.socmt = socmt;
		this.sodt = sodt;
		this.chucvu = chucvu;
		this.tendangnhap = tendangnhap;
		this.matkhau = matkhau;
		this.ytecol = ytecol;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idyte", unique = true, nullable = false)
	public Integer getIdyte() {
		return this.idyte;
	}

	public void setIdyte(Integer idyte) {
		this.idyte = idyte;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idrole")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "hoten", length = 45)
	public String getHoten() {
		return this.hoten;
	}

	public void setHoten(String hoten) {
		this.hoten = hoten;
	}

	@Column(name = "gioitinh", length = 45)
	public String getGioitinh() {
		return this.gioitinh;
	}

	public void setGioitinh(String gioitinh) {
		this.gioitinh = gioitinh;
	}

	@Column(name = "namsinh", length = 45)
	public String getNamsinh() {
		return this.namsinh;
	}

	public void setNamsinh(String namsinh) {
		this.namsinh = namsinh;
	}

	@Column(name = "diachi", length = 45)
	public String getDiachi() {
		return this.diachi;
	}

	public void setDiachi(String diachi) {
		this.diachi = diachi;
	}

	@Column(name = "socmt", length = 45)
	public String getSocmt() {
		return this.socmt;
	}

	public void setSocmt(String socmt) {
		this.socmt = socmt;
	}

	@Column(name = "sodt", length = 45)
	public String getSodt() {
		return this.sodt;
	}

	public void setSodt(String sodt) {
		this.sodt = sodt;
	}

	@Column(name = "chucvu", length = 45)
	public String getChucvu() {
		return this.chucvu;
	}

	public void setChucvu(String chucvu) {
		this.chucvu = chucvu;
	}

	@Column(name = "tendangnhap", length = 45)
	public String getTendangnhap() {
		return this.tendangnhap;
	}

	public void setTendangnhap(String tendangnhap) {
		this.tendangnhap = tendangnhap;
	}

	@Column(name = "matkhau", length = 45)
	public String getMatkhau() {
		return this.matkhau;
	}

	public void setMatkhau(String matkhau) {
		this.matkhau = matkhau;
	}

	@Column(name = "ytecol", nullable = false, length = 45)
	public String getYtecol() {
		return this.ytecol;
	}

	public void setYtecol(String ytecol) {
		this.ytecol = ytecol;
	}

}
