/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.entity;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for Yte entity stored in table yte.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="yte", catalog="qlsuckhoe" )
public class Yte implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="idyte", nullable=false)
    private Integer idyte ; 
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="hoten", length=45)
    private String hoten ;     @Column(name="gioitinh", length=45)
    private String gioitinh ;     @Column(name="namsinh", length=45)
    private String namsinh ;     @Column(name="diachi", length=45)
    private String diachi ;     @Column(name="socmt", length=45)
    private String socmt ;     @Column(name="sodt", length=45)
    private String sodt ;     @Column(name="chucvu", length=45)
    private String chucvu ;     @Column(name="tendangnhap", length=45)
    private String tendangnhap ;     @Column(name="matkhau", length=45)
    private String matkhau ;     @Column(name="idrole")
    private Integer idrole ; // Foreign Key     @Column(name="ytecol", nullable=false, length=45)
    private String ytecol ; 

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Yte() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setIdyte(Integer idyte) {
        this.idyte = idyte ;
    }
	public Integer getIdyte() {
        return this.idyte;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : hoten (VARCHAR) 
	public void setHoten(String hoten) {this.hoten = hoten;}
	public String getHoten() {return this.hoten;}

	//--- DATABASE MAPPING : gioitinh (VARCHAR) 
	public void setGioitinh(String gioitinh) {this.gioitinh = gioitinh;}
	public String getGioitinh() {return this.gioitinh;}

	//--- DATABASE MAPPING : namsinh (VARCHAR) 
	public void setNamsinh(String namsinh) {this.namsinh = namsinh;}
	public String getNamsinh() {return this.namsinh;}

	//--- DATABASE MAPPING : diachi (VARCHAR) 
	public void setDiachi(String diachi) {this.diachi = diachi;}
	public String getDiachi() {return this.diachi;}

	//--- DATABASE MAPPING : socmt (VARCHAR) 
	public void setSocmt(String socmt) {this.socmt = socmt;}
	public String getSocmt() {return this.socmt;}

	//--- DATABASE MAPPING : sodt (VARCHAR) 
	public void setSodt(String sodt) {this.sodt = sodt;}
	public String getSodt() {return this.sodt;}

	//--- DATABASE MAPPING : chucvu (VARCHAR) 
	public void setChucvu(String chucvu) {this.chucvu = chucvu;}
	public String getChucvu() {return this.chucvu;}

	//--- DATABASE MAPPING : tendangnhap (VARCHAR) 
	public void setTendangnhap(String tendangnhap) {this.tendangnhap = tendangnhap;}
	public String getTendangnhap() {return this.tendangnhap;}

	//--- DATABASE MAPPING : matkhau (VARCHAR) 
	public void setMatkhau(String matkhau) {this.matkhau = matkhau;}
	public String getMatkhau() {return this.matkhau;}

	//--- DATABASE MAPPING : idrole (INT) 
	public void setIdrole(Integer idrole) {this.idrole = idrole;}
	public Integer getIdrole() {return this.idrole;}

	//--- DATABASE MAPPING : ytecol (VARCHAR) 
	public void setYtecol(String ytecol) {this.ytecol = ytecol;}
	public String getYtecol() {return this.ytecol;}


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(idyte); 
		sb.append(hoten); 
		sb.append("|"); 
		sb.append(gioitinh); 
		sb.append("|"); 
		sb.append(namsinh); 
		sb.append("|"); 
		sb.append(diachi); 
		sb.append("|"); 
		sb.append(socmt); 
		sb.append("|"); 
		sb.append(sodt); 
		sb.append("|"); 
		sb.append(chucvu); 
		sb.append("|"); 
		sb.append(tendangnhap); 
		sb.append("|"); 
		sb.append(matkhau); 
		sb.append("|"); 
		sb.append(idrole); 
		sb.append("|"); 
		sb.append(ytecol); 
        return sb.toString();
    }
}