/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.repository;

import com.tlu.qlsuckhoe.entity.Nhasanxuat;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Jpa repository for Nhasanxuat.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Repository
public interface NhasanxuatRepository  extends JpaRepository<Nhasanxuat, Integer> {}