/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 22:38:43 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.repository;

import com.tlu.qlsuckhoe.entity.Thietbiyte;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Jpa repository for Thietbiyte.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Repository
public interface ThietbiyteRepository  extends JpaRepository<Thietbiyte, Integer> {}